---
# roles/dns/tasks/main.yml

- name: Update DNS
  route53:
    command: create
    overwrite: yes
    zone: "{{ domain }}"
    record: "www.{{ domain }}"
    type: CNAME
    ttl: 300
    value: "{{ elb_result.elb.dns_name }}"
